version: '3.9'
services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: web-techno-cursach
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5433:5432"
